$ErrorActionPreference = "Stop"

$GeminiConfigDir = Join-Path $env:USERPROFILE ".gemini\config"
$ScriptsDir = Join-Path $GeminiConfigDir "scripts"

New-Item -Path $ScriptsDir -ItemType Directory -Force | Out-Null

$HookCode = @'
#!/usr/bin/env python3
import sys
import json
import os
import subprocess
import socket
import time
import tempfile
import getpass

USER = getpass.getuser()
PORT_FILE = os.path.join(tempfile.gettempdir(), f"lgtm_daemon_{USER}.port")

def get_daemon_conn():
    if not os.path.exists(PORT_FILE):
        return None, None
    try:
        with open(PORT_FILE, "r", encoding="utf-8") as f:
            content = f.read().strip()
        if not content or ":" not in content:
            return None, None
        port_str, token = content.split(":", 1)
        port = int(port_str)
        client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client.settimeout(30.0)
        client.connect(("127.0.0.1", port))
        return client, token
    except Exception:
        return None, None

def spawn_daemon(daemon_script):
    eval_env = os.environ.copy()
    eval_env["AGY_HOOK_BYPASS"] = "1"
    subprocess.Popen(
        [sys.executable, daemon_script],
        env=eval_env,
        start_new_session=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

def main():
    try:
        input_data = sys.stdin.read()
        if not input_data:
            print(json.dumps({"decision": "deny", "reason": "No input provided"}))
            return
            
        payload = json.loads(input_data)
        command_line = payload.get("toolCall", {}).get("args", {}).get("CommandLine", "")

        if os.environ.get("AGY_HOOK_BYPASS") == "1":
            print(json.dumps({"decision": "allow", "reason": "Bypass loop explicitly allowed"}))
            return

        safe_prefixes = (
            "ls ", "ls", "grep ", "head ", "tail ", "find ", "pwd", "whoami",
            "ps ", "ps", "env", "git diff", "git status", "git log", "git show",
            "file ", "stat ", "wc ", "tree ", "jq ", "date", "uname", "cat "
        )
        if command_line.startswith(safe_prefixes):
            print(json.dumps({"decision": "allow", "reason": "Fast-path: Safe read command"}))
            return

        prompt = (
            "You are a second set of eyes reviewing shell commands before they execute. "
            "The commands are generated by an experienced, trusted AI agent actively working on the user's machine. "
            "The agent is highly capable, NOT untrustworthy. You are only here to catch rare, catastrophic oversights.\n\n"
            "GUIDELINES:\n"
            "1. DEFAULT TO ALLOWING the command. Trust the agent's intent. Normal development workflows (creating, modifying, or executing scripts, even in /tmp) are perfectly safe.\n"
            "2. ALLOW all standard tools and complex scripts unconditionally.\n"
            "3. DENY ONLY if the command is a clear and catastrophic mistake (e.g., 'rm -rf /', wiping critical system directories) or an explicit secret leak.\n\n"
            f"Command to evaluate: `{command_line}`\n\n"
            'Respond with ONLY a raw JSON object (no markdown): {"decision": "allow"|"deny", "reason": "<brief reason>"}'
        )

        daemon_script = os.path.join(os.path.dirname(__file__), "lgtm_daemon.py")
        
        client, token = get_daemon_conn()
        if not client:
            if os.path.exists(daemon_script):
                spawn_daemon(daemon_script)
                for _ in range(100):
                    time.sleep(0.1)
                    client, token = get_daemon_conn()
                    if client:
                        break

        llm_response = ""
        if client and token:
            try:
                msg = json.dumps({"token": token, "prompt": prompt})
                client.sendall(msg.encode("utf-8"))
                llm_response = client.recv(65536).decode("utf-8").strip()
            except Exception:
                llm_response = ""
            finally:
                client.close()

        if not llm_response:
            # Fallback to slow mode
            eval_env = os.environ.copy()
            eval_env["AGY_HOOK_BYPASS"] = "1"
            result = subprocess.run(
                ["agy", "-p", prompt, "--model", "gemini-3.8-flash-low", "--new-project"],
                capture_output=True, text=True, env=eval_env, cwd=tempfile.gettempdir()
            )
            llm_response = result.stdout.strip()
        
        if not llm_response:
            print(json.dumps({"decision": "deny", "reason": "Empty response from Gemini API"}))
            return
            
        try:
            parsed_response = json.loads(llm_response)
            if "decision" in parsed_response:
                print(json.dumps(parsed_response))
            else:
                print(json.dumps({"decision": "deny", "reason": "Invalid response schema"}))
        except json.JSONDecodeError:
            print(json.dumps({"decision": "deny", "reason": f"Failed to parse LLM JSON: {llm_response}"}))
            
    except Exception as e:
        print(json.dumps({"decision": "deny", "reason": f"Hook exception: {str(e)}"}))

if __name__ == "__main__":
    main()
'@

$DaemonCode = @'
import socket
import os
import sys
import subprocess
import json
import time
import tempfile
import getpass
import secrets
import atexit

USER = getpass.getuser()
PORT_FILE = os.path.join(tempfile.gettempdir(), f"lgtm_daemon_{USER}.port")

def spawn_agy():
    env = os.environ.copy()
    env["AGY_HOOK_BYPASS"] = "1"
    proc = subprocess.Popen(
        ["agy", "--input-format", "stream-json", "--output-format", "stream-json", "--model", "gemini-3.8-flash-low", "--new-project"],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, env=env, cwd=tempfile.gettempdir()
    )
    while True:
        line = proc.stdout.readline()
        if not line or "init" in line:
            break
    return proc

def main():
    if os.path.exists(PORT_FILE):
        try:
            with open(PORT_FILE, "r", encoding="utf-8") as f:
                port_str, _ = f.read().strip().split(":", 1)
            test_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            test_sock.settimeout(1.0)
            test_sock.connect(("127.0.0.1", int(port_str)))
            test_sock.close()
            return
        except Exception:
            try:
                os.remove(PORT_FILE)
            except OSError:
                pass

    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.bind(("127.0.0.1", 0))
    port = server.getsockname()[1]
    server.listen(5)

    auth_token = secrets.token_hex(16)
    with open(PORT_FILE, "w", encoding="utf-8") as f:
        f.write(f"{port}:{auth_token}")

    proc = spawn_agy()
    count = 0

    def cleanup():
        try:
            if proc and proc.poll() is None:
                proc.terminate()
                try:
                    proc.wait(timeout=3)
                except Exception:
                    proc.kill()
        except Exception:
            pass
        if os.path.exists(PORT_FILE):
            try:
                os.remove(PORT_FILE)
            except OSError:
                pass

    atexit.register(cleanup)

    while True:
        conn = None
        try:
            conn, _ = server.accept()
            data = conn.recv(65536).decode("utf-8")
            if not data:
                continue

            req = json.loads(data)
            if req.get("token") != auth_token:
                conn.sendall(b'{"decision": "deny", "reason": "unauthorized"}')
                continue

            # Check if child worker process is still alive, respawn if terminated
            if proc.poll() is not None:
                proc = spawn_agy()

            prompt = req.get("prompt", "")
            payload = {"event": "user", "message": {"content": prompt}}

            try:
                proc.stdin.write(json.dumps(payload) + "\n")
                proc.stdin.flush()
            except (BrokenPipeError, OSError):
                # Worker died or pipe broken; respawn and retry once
                proc = spawn_agy()
                proc.stdin.write(json.dumps(payload) + "\n")
                proc.stdin.flush()

            response = ""
            while True:
                line = proc.stdout.readline()
                if not line:
                    break
                if "result" in line.lower() and "response" in line.lower():
                    try:
                        res = json.loads(line)
                        result_obj = res.get("result", {})
                        if result_obj.get("status") == "ERROR":
                            err_msg = result_obj.get("error", "Unknown error")
                            response = f'{{"decision": "deny", "reason": "API Error: {err_msg}"}}'
                        else:
                            response = result_obj.get("response", "")
                    except Exception:
                        pass
                    break

            if response.startswith("```json"):
                response = response.split("```json")[1].split("```")[0].strip()
            elif response.startswith("```"):
                response = response.split("```")[1].split("```")[0].strip()

            conn.sendall(response.encode("utf-8"))

            count += 1
            if count >= 20:
                proc.terminate()
                try:
                    proc.wait(timeout=5)
                except Exception:
                    proc.kill()
                proc = spawn_agy()
                count = 0

        except Exception as e:
            try:
                if conn:
                    conn.sendall(f'{{"decision": "deny", "reason": "daemon error: {str(e)}"}}\n'.encode("utf-8"))
            except Exception:
                pass
        finally:
            if conn:
                try:
                    conn.close()
                except Exception:
                    pass

if __name__ == "__main__":
    main()
'@

Set-Content -Path (Join-Path $ScriptsDir "ai_approval_hook.py") -Value $HookCode -Encoding UTF8
Set-Content -Path (Join-Path $ScriptsDir "lgtm_daemon.py") -Value $DaemonCode -Encoding UTF8

$HooksJsonPath = Join-Path $GeminiConfigDir "hooks.json"
if (Test-Path $HooksJsonPath) {
    Copy-Item -Path $HooksJsonPath -Destination "$HooksJsonPath.bak" -Force
}

$HooksJsonCode = @"
{
  "ai-approval-hook": {
    "PreToolUse": [
      {
        "matcher": "run_command",
        "hooks": [
          {
            "type": "command",
            "command": "python ./scripts/ai_approval_hook.py",
            "timeout": 45
          }
        ]
      }
    ]
  }
}
"@

Set-Content -Path $HooksJsonPath -Value $HooksJsonCode -Encoding UTF8

Write-Host "✅ LGTM installed! All run_command tool calls will now be evaluated by the LLM." -ForegroundColor Green
