#!/usr/bin/env python3
import sys
import json
import os
import subprocess
import socket
import time
import tempfile
import getpass
import shutil

USER = getpass.getuser()
PORT_FILE = os.path.join(tempfile.gettempdir(), f"lgtm_daemon_{USER}.port")
LGTM_GEMINI_DIR = os.path.join(tempfile.gettempdir(), f"lgtm_gemini_{USER}")

def setup_isolated_gemini_dir():
    cli_dir = os.path.join(LGTM_GEMINI_DIR, "antigravity-cli")
    os.makedirs(cli_dir, exist_ok=True)
    real_gemini = os.path.expanduser("~/.gemini/antigravity-cli")
    for item in ("antigravity-oauth-token", "settings.json"):
        src = os.path.join(real_gemini, item)
        dst = os.path.join(cli_dir, item)
        if os.path.exists(src):
            if os.path.islink(dst) or os.path.exists(dst):
                try:
                    os.remove(dst)
                except OSError:
                    pass
            try:
                os.symlink(src, dst)
            except (OSError, NotImplementedError, AttributeError):
                try:
                    shutil.copy2(src, dst)
                except OSError:
                    pass

def get_daemon_conn():
    if not os.path.exists(PORT_FILE):
        return None, None
    try:
        with open(PORT_FILE, "r", encoding="utf-8") as f:
            content = f.read().strip()
        if not content or ":" not in content:
            return None, None
        port_str, token = content.split(":", 1)
        port = int(port_str)
        client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client.settimeout(30.0)
        client.connect(("127.0.0.1", port))
        return client, token
    except Exception:
        return None, None

def spawn_daemon(daemon_script):
    eval_env = os.environ.copy()
    eval_env["AGY_HOOK_BYPASS"] = "1"
    subprocess.Popen(
        [sys.executable, daemon_script],
        env=eval_env,
        start_new_session=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

def main():
    try:
        input_data = sys.stdin.read()
        if not input_data:
            print(json.dumps({"decision": "deny", "reason": "No input provided"}))
            return
            
        payload = json.loads(input_data)
        command_line = payload.get("toolCall", {}).get("args", {}).get("CommandLine", "")

        if os.environ.get("AGY_HOOK_BYPASS") == "1":
            print(json.dumps({"decision": "allow", "reason": "Bypass loop explicitly allowed"}))
            return

        safe_prefixes = (
            "ls ", "ls", "grep ", "head ", "tail ", "find ", "pwd", "whoami",
            "ps ", "ps", "env", "git diff", "git status", "git log", "git show",
            "file ", "stat ", "wc ", "tree ", "jq ", "date", "uname", "cat ",
            "echo ", "sqlite3 "
        )
        if command_line.startswith(safe_prefixes):
            print(json.dumps({"decision": "allow", "reason": "Fast-path: Safe read command"}))
            return

        prompt = (
            "You are a second set of eyes reviewing shell commands before they execute. "
            "The commands are generated by an experienced, trusted AI agent actively working on the user's machine. "
            "The agent is highly capable, NOT untrustworthy. You are only here to catch rare, catastrophic oversights.\n\n"
            "GUIDELINES:\n"
            "1. DEFAULT TO ALLOWING the command. Trust the agent's intent. Normal development workflows (creating, modifying, or executing scripts, even in /tmp) are perfectly safe.\n"
            "2. ALLOW all standard tools and complex scripts unconditionally.\n"
            "3. DENY ONLY if the command is a clear and catastrophic mistake (e.g., 'rm -rf /', wiping critical system directories) or an explicit secret leak.\n\n"
            f"Command to evaluate: `{command_line}`\n\n"
            'Respond with ONLY a raw JSON object (no markdown): {"decision": "allow"|"deny", "reason": "<brief reason>"}'
        )

        daemon_script = os.path.join(os.path.dirname(__file__), "lgtm_daemon.py")
        
        client, token = get_daemon_conn()
        if not client:
            if os.path.exists(daemon_script):
                spawn_daemon(daemon_script)
                for _ in range(100):
                    time.sleep(0.1)
                    client, token = get_daemon_conn()
                    if client:
                        break

        llm_response = ""
        if client and token:
            try:
                msg = json.dumps({"token": token, "prompt": prompt})
                client.sendall(msg.encode("utf-8"))
                llm_response = client.recv(65536).decode("utf-8").strip()
            except Exception:
                llm_response = ""
            finally:
                client.close()

        if not llm_response:
            # Fallback to slow mode with isolated gemini directory
            setup_isolated_gemini_dir()
            eval_env = os.environ.copy()
            eval_env["AGY_HOOK_BYPASS"] = "1"
            result = subprocess.run(
                ["agy", f"--gemini_dir={LGTM_GEMINI_DIR}", "-p", prompt, "--model", "gemini-3.8-flash-low"],
                capture_output=True, text=True, env=eval_env, cwd=tempfile.gettempdir()
            )
            llm_response = result.stdout.strip()
        
        if not llm_response:
            print(json.dumps({"decision": "deny", "reason": "Empty response from Gemini API"}))
            return
            
        try:
            parsed_response = json.loads(llm_response)
            if "decision" in parsed_response:
                print(json.dumps(parsed_response))
            else:
                print(json.dumps({"decision": "deny", "reason": "Invalid response schema"}))
        except json.JSONDecodeError:
            print(json.dumps({"decision": "deny", "reason": f"Failed to parse LLM JSON: {llm_response}"}))
            
    except Exception as e:
        print(json.dumps({"decision": "deny", "reason": f"Hook exception: {str(e)}"}))

if __name__ == "__main__":
    main()

